# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 13:58
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBrief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('article_cut', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u7b80\u4ecb')),
                ('article_from', models.CharField(max_length=50, verbose_name='\u6765\u6e90')),
                ('pub_date', models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_text', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u6587\u7ae0')),
                ('articlebrief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot.ArticleBrief')),
            ],
        ),
    ]
