# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlebrief',
            name='article_cut',
            field=models.TextField(max_length=1000, verbose_name='\u7b80\u4ecb'),
        ),
    ]
