# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot', '0002_auto_20160321_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlebrief',
            name='article_title',
            field=models.CharField(max_length=200, verbose_name='\u6807\u9898'),
        ),
    ]
